name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install Django
        
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

    - name: Install dependencies
      run: |
        pip install psycopg2-binary

    - name: Install dependencies
      run: |
        pip install django-environ
        
    - name: Debug variable
      run: echo $VARIABLE_NAME
        
    - name: Set environment variables
      run: |
        echo "VARIABLE_NAME=value" >> $GITHUB_ENV


    - name: Run tests
      working-directory: final_project
      run: python manage.py test
